# Basic of python 
#Variable = A container for a value  (string, integer, float, boolean)
#    a variable behave as if it was the value it contain 


print("yuvraj")
print("i like pizza ")

first_name = "Bro"
print(first_name)

# these are strings = sequence of a character

food = "pizza"
email = "yuvraj123@gmail.com"

print(f"Hello {first_name}")
print(f"i like {food}")
print(f" your email is {email}")

#integer
age = 25
quantity = 3
num_of_students = 30

print(f"you are { age } year old")
print(f"you are buying {quantity} item")
print(f"your class has {num_of_students} students")

#Float
price = 10.99
gpa= 3.2
distance = 5.5

print(f"the price is ${price}")
print(f"your gpa is : {gpa}")
print(f"you run {distance} km ")

#boolean = True and False

is_student = False

#print(f" are you a student? {is_student} ")

if is_student:
    print("You are a student")
else:
    print("you are not a student")







